- name: Setup Camera Loopback and Services
  hosts: laser
  become: true
  tasks:
    # Install required packages
    - name: Install required packages
      apt:
        name:
          - python3-opencv
          - ffmpeg
          - v4l2loopback-dkms
          - v4l2loopback-utils

    # Load v4l2loopback module
    - name: Load v4l2loopback kernel module
      modprobe:
        name: v4l2loopback
        params: "devices=2 video_nr=10,11 card_label='Loopback1 Loopback2' exclusive_caps=1"

    # Ensure v4l2loopback is loaded on boot
    - name: Ensure v4l2loopback loads on boot
      lineinfile:
        path: /etc/modules
        line: "v4l2loopback devices=2 video_nr=10,11 card_label='Loopback1,Loopback2' exclusive_caps=1"
        state: present

    # Configure X11 to stream video to loopback and display
    - name: Create .xinitrc to stream video to loopback and display
      copy:
        content: |
          #!/bin/bash
          ffmpeg -i /dev/video0 -f v4l2 /dev/video10 &
          exec ffplay /dev/video10
        dest: /root/.xinitrc
        mode: '0755'
        owner: root
        group: root

    # Create systemd service to start X11 and ffmpeg
    - name: Create systemd service to start X11 and ffmpeg
      copy:
        content: |
          [Unit]
          Description=Start X11 and run ffmpeg
          After=multi-user.target

          [Service]
          ExecStart=/usr/bin/startx
          User=root
          WorkingDirectory=/root
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/x11-ffmpeg.service
        mode: '0644'

    - name: Enable and start X11 ffmpeg service
      systemd:
        name: x11-ffmpeg.service
        enabled: true
        state: started

    # Create camera-loop service file
    - name: Create camera-loop service file
      copy:
        content: |
          [Unit]
          Description=Loop /dev/video0 to /dev/video10 and /dev/video11
          After=multi-user.target

          [Service]
          ExecStart=/usr/bin/ffmpeg -f v4l2 -input_format mjpeg -framerate 10 -video_size 800x480 -i /dev/video0 \
          -filter_complex "[0:v]split=2[out1][out2]" \
          -map "[out1]" -f v4l2 -vcodec mjpeg /dev/video10 \
          -map "[out2]" -f v4l2 -vcodec mjpeg /dev/video11
          Restart=always
          RestartSec=2
          User=pi
          WorkingDirectory=/home/pi

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/camera-loop.service
        mode: '0644'

    # Enable and start camera-loop service
    - name: Enable and start camera-loop service
      systemd:
        name: camera-loop.service
        enabled: true
        state: started

