- hosts: laser
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-zmq
          - python3-pyqt5
          - python3-rpi-lgpio
          - python3-opencv
          - watchdog
        state: present
        update_cache: yes

    # Ensure /opt/hal directory exists
    - name: Create /opt/hal directory
      file:
        path: /opt/hal
        state: directory
        owner: kiosk
        group: kiosk
        mode: '0755'

    # Copy hal.py to /opt/hal
    - name: Copy hal.py to /opt/hal
      copy:
        src: /home/nps/projects/laser-enclosure/src/hal.py
        dest: /opt/hal/hal.py
        owner: kiosk
        group: kiosk
        mode: '0755'

    # Create HAL GPIO and Sensor systemd service file
    - name: Create HAL GPIO and Sensor systemd service file
      copy:
        content: |
          [Unit]
          Description=HAL GPIO and Sensor Service
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3 /opt/hal/hal.py
          Restart=on-failure
          RestartSec=2
          WatchdogSec=5s
          NotifyAccess=all
          StandardOutput=journal
          StandardError=journal
          TimeoutStartSec=10

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/hal-opt.service
        mode: '0644'

    # Enable and start HAL GPIO and Sensor service
    - name: Enable and start HAL GPIO and Sensor service
      systemd:
        name: hal-opt.service
        enabled: true
        state: started


