- hosts: laser
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-zmq
          - python3-pyqt5
          - python3-rpi-lgpio
          - python3-opencv
          - watchdog
        state: present
        update_cache: yes

    - name: Ensure /opt/kiosk directory exists
      file:
        path: /opt/kiosk
        state: directory
        owner: kiosk
        group: kiosk
        mode: '0755'

    - name: Deploy full application to /opt/kiosk
      copy:
        src: "/home/nps/projects/laser-enclosure/src/"
        dest: "/opt/kiosk/"
        owner: kiosk
        group: kiosk
        mode: '0755'

    - name: Create HAL GPIO and Sensor systemd service file
      copy:
        content: |
          [Unit]
          Description=HAL GPIO and Sensor Service
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3 /opt/kiosk/run_hal.py
          Restart=on-failure
          RestartSec=2
          WatchdogSec=5s
          NotifyAccess=all
          StandardOutput=journal
          StandardError=journal
          StartLimitIntervalSec=60
          StartLimitBurst=5
          TimeoutStartSec=10
          KillSignal=SIGINT
          User=kiosk
          Group=kiosk
          WorkingDirectory=/opt/kiosk

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/hal.service
        mode: '0644'

    - name: Enable and start HAL GPIO and Sensor service
      systemd:
        name: hal.service
        enabled: true
        state: started

    - name: Create Supervisor (Control Logic) systemd service file
      copy:
        content: |
          [Unit]
          Description=Laser Control Logic (Supervisor)
          After=network.target hal.service

          [Service]
          ExecStart=/usr/bin/python3 /opt/kiosk/run_control.py
          Restart=on-failure
          RestartSec=2
          StandardOutput=journal
          StandardError=journal
          User=kiosk
          Group=kiosk
          WorkingDirectory=/opt/kiosk

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/control.service
        mode: '0644'

    - name: Enable and start Supervisor (Control Logic) service
      systemd:
        name: control.service
        enabled: true
        state: started

- name: Install GUI dependencies and prepare autostart
  hosts: laser
  become: yes
  tasks:
    - name: Install GUI and Python dependencies
      apt:
        name:
          - xinit
          - x11-xserver-utils
          - python3-pyqt5
          - python3-pip
          - fonts-dejavu
        state: present
        update_cache: yes

    - name: Create autostart X session script
      copy:
        dest: /home/kiosk/.xsession
        mode: '0755'
        owner: kiosk
        group: kiosk
        content: |
          #!/bin/bash
          xset s off
          xset -dpms
          xset s noblank
          exec /usr/bin/python3 /opt/kiosk/gui/main.py

    - name: Ensure .xinitrc matches .xsession
      file:
        src: /home/kiosk/.xsession
        dest: /home/kiosk/.xinitrc
        state: link
        owner: kiosk
        group: kiosk

    - name: Ensure startx runs on login
      lineinfile:
        path: /home/kiosk/.bash_profile
        line: '[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx'
        create: yes
        owner: kiosk
        group: kiosk

    - name: Ensure Xauthority file exists
      file:
        path: /home/kiosk/.Xauthority
        state: touch
        owner: kiosk
