- hosts: laser
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-zmq
          - python3-pyqt5
          - python3-rpi-lgpio
          - python3-opencv
          - watchdog

        state: present
        update_cache: yes

    # Create directory for kiosk user services
    - name: Create directory for kiosk user services
      file:
        path: /home/kiosk/services
        state: directory
        owner: kiosk
        group: kiosk
        mode: '0755'

    # Copy GPIO service file
    - name: Copy GPIO service file
      copy:
        dest: /home/kiosk/services/hal.py
        src: /home/nps/projects/laser-enclosure/src/hal.py
        owner: kiosk
        group: kiosk
        mode: '0755'

    # Create GPIO systemd service file
    - name: Create GPIO systemd service file
      copy:
        content: |
          [Unit]
          Description=GPIO Service
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3 /home/kiosk/services/hal.py
          Restart=always
          RestartSec=2
          User=kiosk
          WorkingDirectory=/home/kiosk/services

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/hal.service
        mode: '0644'

    # Enable and start GPIO service
    - name: Enable and start GPIO service
      systemd:
        name: hal.service
        enabled: true
        state: started
