- hosts: laser
  become: yes
  vars:
    kiosk_user: kiosk
    app_dir: /opt/kiosk

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-zmq
          - python3-pyqt5
          - python3-rpi-lgpio
          - python3-opencv
          - watchdog
        state: present
        update_cache: yes

    - name: Install Python libraries system wide
      pip:
        name:
        - adafruit-circuitpython-ads1x15
        - adafruit-circuitpython-mcp230xx
        - adafruit-circuitpython-bme280
        - adafruit-circuitpython-seesaw
        extra_args: --break-system-packages

    - name: Ensure /opt/kiosk directory exists
      file:
        path: /opt/kiosk
        state: directory
        owner: kiosk
        group: kiosk
        mode: '0755'

    - name: Deploy full application to /opt/kiosk
      copy:
        src: "/home/nps/projects/laser-enclosure/src/"
        dest: "/opt/kiosk/"
        owner: kiosk
        group: kiosk
        mode: '0755'

    - name: Create HAL GPIO and Sensor systemd service
      copy:
        dest: /etc/systemd/system/kiosk-hal.service
        mode: '0644'
        content: |
          [Unit]
          Description=HAL GPIO and Sensor Service
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3 /opt/kiosk/run_hal.py
          Restart=on-failure
          RestartSec=2
          WatchdogSec=5s
          NotifyAccess=all
          StandardOutput=journal
          StandardError=journal
          StartLimitBurst=5
          TimeoutStartSec=10
          KillSignal=SIGINT
          User=kiosk
          Group=kiosk
          WorkingDirectory=/opt/kiosk
          SyslogIdentifier=kiosk-hal

    - name: Create Control layer systemd service
      copy:
        dest: /etc/systemd/system/kiosk-control.service
        mode: '0644'
        content: |
          [Unit]
          Description=Laser Control Logic (Supervisor)
          After=network.target kiosk-hal.service

          [Service]
          ExecStart=/usr/bin/python3 /opt/kiosk/run_control.py
          Restart=on-failure
          RestartSec=2
          StandardOutput=journal
          StandardError=journal
          User=kiosk
          Group=kiosk
          WorkingDirectory=/opt/kiosk
          SyslogIdentifier=kiosk-control

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start kiosk-hal service
      systemd:
        name: kiosk-hal.service
        enabled: true
        state: started

    - name: Enable and start kiosk-control service
      systemd:
        name: kiosk-control.service
        enabled: true
        state: started

    - name: Install GUI and Python dependencies
      apt:
        name:
          - xinit
          - x11-xserver-utils
          - python3-pyqt5
          - python3-pip
          - fonts-dejavu
        state: present
        update_cache: yes

    - name: Create .xsession for GUI autostart
      copy:
        dest: /home/kiosk/.xsession
        mode: '0755'
        owner: kiosk
        group: kiosk
        content: |
          #!/bin/bash
          xset s off
          xset -dpms
          xset s noblank
          exec /usr/bin/python3 /opt/kiosk/gui/main.py

    - name: Create .xinitrc for GUI autostart
      copy:
        dest: /home/kiosk/.xinitrc
        mode: '0755'
        owner: kiosk
        group: kiosk
        content: |
          #!/bin/bash
          xset s off
          xset -dpms
          xset s noblank
          exec /opt/kiosk/run_gui.py

    - name: Ensure startx runs on login
      lineinfile:
        path: /home/kiosk/.bash_profile
        line: '[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx'
        create: yes
        owner: kiosk
        group: kiosk

    - name: Ensure Xauthority file exists
      file:
        path: /home/kiosk/.Xauthority
        state: touch
        owner: kiosk
        group: kiosk

    - name: Ensure getty@tty1 override directory exists
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        state: directory
        mode: '0755'

    - name: Enable autologin for kiosk on tty1
      copy:
        dest: /etc/systemd/system/getty@tty1.service.d/override.conf
        mode: '0644'
        owner: root
        group: root
        content: |
          [Service]
          ExecStart=
          ExecStart=-/sbin/agetty --autologin kiosk --noclear %I $TERM

    - name: Reload systemd and restart getty@tty1
      systemd:
        daemon_reload: yes
        name: getty@tty1.service
        state: restarted
        enabled: true

    - name: Ensure getty on tty2 is enabled
      systemd:
        name: getty@tty2.service
        enabled: true
        state: started


    - name: Enable kiosk-hal service
      systemd:
        name: kiosk-hal.service
        enabled: true

    - name: Restart kiosk-hal service after deploy
      systemd:
        name: kiosk-hal.service
        state: restarted

    - name: Enable kiosk-control service
      systemd:
        name: kiosk-control.service
        enabled: true

    - name: Restart kiosk-control service after deploy
      systemd:
        name: kiosk-control.service
        state: restarted