- hosts: laser
  become: yes
  vars:
    kiosk_user: kiosk
    app_dir: /opt/kiosk
    
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-zmq
          - python3-pyqt5
          - python3-rpi-lgpio
          - python3-opencv
          - watchdog
        state: present
        update_cache: yes

    - name: Ensure /opt/kiosk directory exists
      file:
        path: /opt/kiosk
        state: directory
        owner: kiosk
        group: kiosk
        mode: '0755'

    - name: Deploy full application to /opt/kiosk
      copy:
        src: "/home/nps/projects/laser-enclosure/src/"
        dest: "/opt/kiosk/"
        owner: kiosk
        group: kiosk
        mode: '0755'

    - name: Create HAL GPIO and Sensor systemd service
      copy:
        dest: /etc/systemd/system/kiosk-hal.service
        mode: '0644'
        content: |
          [Unit]
          Description=HAL GPIO and Sensor Service
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3 /opt/kiosk/run_hal.py
          Restart=on-failure
          RestartSec=2
          WatchdogSec=5s
          NotifyAccess=all
          StandardOutput=journal
          StandardError=journal
          StartLimitIntervalSec=60
          StartLimitBurst=5
          TimeoutStartSec=10
          KillSignal=SIGINT
          User=kiosk
          Group=kiosk
          WorkingDirectory=/opt/kiosk
