- name: Setup Raspberry Pi
  hosts: laser
  become: true
  tasks:

    # Update packages
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade all packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600

    # Install required packages
    - name: Install required packages
      apt:
        name:
          - screen
          - python3-pip
          - git
          - python3-opencv
          - xserver-xorg
          - xinit
          - ffmpeg
          - v4l2loopback-dkms
          - v4l2loopback-utils
        update_cache: true

    # Ensure Wayland is not used (skip removing Wayland libraries)
    - name: Disable Wayland by ensuring X11 is used
      lineinfile:
        path: /etc/environment
        line: "XDG_SESSION_TYPE=x11"
        state: present

    # Load v4l2loopback module
    - name: Load v4l2loopback kernel module
      modprobe:
        name: v4l2loopback
        params: "devices=2 video_nr=10,11 card_label='Loopback1 Loopback2' exclusive_caps=1"

    # Ensure v4l2loopback is loaded on boot
    - name: Ensure v4l2loopback loads on boot
      lineinfile:
        path: /etc/modules
        line: "v4l2loopback devices=2 video_nr=10,11 card_label='Loopback1,Loopback2' exclusive_caps=1"
        state: present

    # Configure X11 to stream video to loopback and display
    - name: Create .xinitrc to stream video to loopback and display
      copy:
        content: |
          #!/bin/bash
          ffmpeg -i /dev/video0 -f v4l2 /dev/video10 &
          exec ffplay /dev/video10
        dest: /root/.xinitrc
        mode: '0755'
        owner: root
        group: root

    - name: Create systemd service to start X11 and ffmpeg
      copy:
        content: |
          [Unit]
          Description=Start X11 and run ffmpeg
          After=multi-user.target

          [Service]
          ExecStart=/usr/bin/startx
          User=root
          WorkingDirectory=/root
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/x11-ffmpeg.service
        mode: '0644'

    - name: Enable and start X11 ffmpeg service
      systemd:
        name: x11-ffmpeg.service
        enabled: true
        state: started

    # Configure HDMI settings
    - name: Add HDMI configuration to /boot/firmware/config.txt
      blockinfile:
        path: /boot/firmware/config.txt
        marker: "# {mark} ANSIBLE MANAGED BLOCK HDMI CONFIGURATION"
        block: |
          hdmi_force_hotplug=1
          hdmi_group=2
          hdmi_mode=87
          hdmi_cvt=800 480 60 6 0 0 0
          hdmi_drive=1

    # Configure touchscreen transformation matrix
    - name: Add touchscreen transformation matrix
      copy:
        content: |
          Section "InputClass"
              Identifier "Touchscreen Calibration"
              MatchIsTouchscreen "on"
              Option "TransformationMatrix" "1 0 0 0 -1 1 0 0 1"
          EndSection
        dest: /etc/X11/xorg.conf.d/99-touchscreen-calibration.conf
        mode: '0644'

    # Placeholder for additional tasks
    - name: Setup camera stuff (placeholder)
      debug:
        msg: "Add camera setup steps here"

    # Create camera-loop service file
    - name: Create camera-loop service file
      copy:
        content: |
          [Unit]
          Description=Loop /dev/video0 to /dev/video10 and /dev/video11
          After=multi-user.target

          [Service]
          ExecStart=/usr/bin/ffmpeg -f v4l2 -input_format mjpeg -framerate 10 -video_size 800x480 -i /dev/video0 \
          -filter_complex "[0:v]split=2[out1][out2]" \
          -map "[out1]" -f v4l2 -vcodec mjpeg /dev/video10 \
          -map "[out2]" -f v4l2 -vcodec mjpeg /dev/video11
          Restart=always
          RestartSec=2
          User=pi
          WorkingDirectory=/home/pi

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/camera-loop.service
        mode: '0644'

    # Enable and start camera-loop service
    - name: Enable and start camera-loop service
      systemd:
        name: camera-loop.service
        enabled: true
        state: started

    # Download Meerkat tarball
    - name: Download Meerkat tarball
      get_url:
        url: https://github.com/meerk40t/meerk40t/releases/download/0.9.7030/MeerK40t_Pi64.tar
        dest: /tmp/MeerK40t_Pi64.tar
        mode: '0644'

    # Extract MeerK40t binary to /usr/local/bin
    - name: Extract MeerK40t binary to /usr/local/bin
      unarchive:
        src: /tmp/MeerK40t_Pi64.tar
        dest: /usr/local/bin
        remote_src: true
        extra_opts:
          - --strip-components=1
          - --wildcards
          - MeerK40t_Pi64/MeerK40t

    # Create Meerkat service file
    - name: Create Meerkat service file
      copy:
        content: |
          [Unit]
          Description=Meerkat Service
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/MeerK40t --config /etc/meerkat/config.yaml
          Restart=always
          RestartSec=2
          User=root
          WorkingDirectory=/etc/meerkat

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/meerkat.service
        mode: '0644'

    # Create Meerkat configuration directory
    - name: Create Meerkat configuration directory
      file:
        path: /etc/meerkat
        state: directory
        mode: '0755'

    # Create Meerkat config.yaml
    - name: Create Meerkat config.yaml
      copy:
        dest: /etc/meerkat/config.yaml
        mode: '0644'
        content: |
          server:
            host: 0.0.0.0
            port: 7020

          broadcast:
            enabled: true
            port: 7020
            interval: 5  # Every 5 seconds broadcast "hey I'm here" on the network

          device:
            type: grbl
            usb_index: 0

          logging:
            level: info

    # Enable and start Meerkat service
    - name: Enable and start Meerkat service
      systemd:
        name: meerkat.service
        enabled: true
        state: started
