- name: Setup Raspberry Pi
  hosts: laser
  become: true
  tasks:

    - name: Enable SSH
      shell: systemctl enable ssh && systemctl start ssh
      when: ansible_service_mgr == 'systemd'

    # Install required packages
    - name: Install required packages
      apt:
        name:
          - socat
          - python3-pip
          - git
        update_cache: true


    # Switch to systemd-networkd
    - name: Include networking tasks
      include_tasks: networking.yaml

    # Create socat service file
    - name: Create socat service file
      copy:
        content: |
          [Unit]
          Description=Socat Serial to Network Bridge
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/bin/socat -d -d TCP-LISTEN:2000,reuseaddr,fork FILE:/dev/ttyACM0,rawer
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/socat.service
        mode: '0644'

    - name: Enable and start socat
      systemd:
        name: socat
        enabled: true
        state: started

    # Placeholder for additional tasks
    - name: Setup camera stuff (placeholder)
      debug:
        msg: "Add camera setup steps here"