- name: Setup Raspberry Pi
  hosts: laser
  become: true
  tasks:
      
    # Update packages
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade all packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600
        
    # Install required packages
    - name: Install required packages
      apt:
        name:
          - socat
          - python3-pip
          - git
        update_cache: true

    # Create socat service file
    - name: Create socat service file
      copy:
        content: |
          [Unit]
          Description=Socat Serial to Network Bridge
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/bin/socat -d -d TCP-LISTEN:2000,reuseaddr,fork FILE:/dev/ttyACM0,rawer
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/socat.service
        mode: '0644'

    - name: Enable and start socat
      systemd:
        name: socat
        enabled: true
        state: started

    # Placeholder for additional tasks
    - name: Setup camera stuff (placeholder)
      debug:
        msg: "Add camera setup steps here"