- name: Deploy Meerkat Service
  hosts: laser
  become: true
  tasks:

    - name: Check if Meerk40t is already installed in kiosk venv
      command: /home/kiosk/venv/bin/pip show meerk40t
      register: meerk40t_installed
      ignore_errors: yes

    - block:
        - name: Install Meerk40t via pip in kiosk venv
          pip:
            name: meerk40t
            state: latest
            virtualenv: /home/kiosk/venv

        - name: Deploy Meerkat systemd service
          copy:
            content: |
              [Unit]
              Description=Meerk40t Laser Cutter Control
              After=network.target

              [Service]
              ExecStart=/home/kiosk/venv/bin/meerk40t --no-gui
              Restart=always
              User=kiosk
              WorkingDirectory=/home/kiosk

              [Install]
              WantedBy=multi-user.target
            dest: /etc/systemd/system/meerkat.service
            mode: '0644'

        - name: Reload systemd
          systemd:
            daemon_reload: yes

        - name: Enable and restart Meerkat service
          systemd:
            name: meerkat.service
            enabled: yes
            state: restarted
      when: meerk40t_installed.rc != 0