- name: Deploy Meerkat Service
  hosts: laser
  become: true
  tasks:

  - block:
      - name: Install dependencies for Meerk40t
        apt:
          name:
          - libopencv-dev
          - python3-pil
          - python3-opencv
          - python3-ezdxf
          - libopenblas0
          - libopenjp2-7
          state: present
          update_cache: yes

      - name: Install Meerk40t from pip
        pip:
          name: git+https://github.com/meerk40t/meerk40t.git@0.9.9000
          executable: pip3
          extra_args: --break-system-packages

      - name: Reload systemd
        systemd:
          daemon_reload: yes
