- name: Setup Raspberry Pi
  hosts: laser
  become: true
  tasks:

    # Update packages
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade all packages
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600

    # Install required packages
    - name: Install required packages
      apt:
        name:
          - xserver-xorg
          - xinit
          - screen
          - git
          - vim
          - python3-pip
          - python3-opencv
          - python3-zmq
          - python3-pyqt5
          - python3-rpi-lgpio
          - python3-sdnotify
          - watchdog
          - xserver-xorg-legacy
        update_cache: true

    - name: Install Python libraries system wide
      pip:
        name: 
        - Adafruit_CircuitPython_DHT
        - adafruit-circuitpython-ads1x15
        - adafruit-circuitpython-mcp230xx 
        extra_args: --break-system-packages

    # Ensure Wayland is not used (skip removing Wayland libraries)
    - name: Disable Wayland by ensuring X11 is used
      lineinfile:
        path: /etc/environment
        line: "XDG_SESSION_TYPE=x11"
        state: present

    # Configure config.txt for Raspberry Pisu
    - name: Overwrite /boot/config.txt with custom settings
      copy:
        dest: /boot/config.txt
        mode: '0644'
        content: |
          dtparam=i2c_arm=on
          auto_initramfs=1
          arm_64bit=1
          arm_boost=1
          disable_overscan=1
          disable_splash=0
          framebuffer_swap=0
          camera_auto_detect=1
          hdmi_force_hotplug=1
          hdmi_group=2
          hdmi_mode=87
          hdmi_cvt=800 480 60 6 0 0 0
          hdmi_drive=2
          dtoverlay=vc4-kms-v3d

    - name: Add touchscreen transformation matrix
      copy:
        content: |
          Section "InputClass"
              Identifier "Touchscreen Calibration"
              MatchIsTouchscreen "on"
              Option "TransformationMatrix" "1 0 0 0 -1 1 0 0 1"
          EndSection
        dest: /etc/X11/xorg.conf.d/99-touchscreen-calibration.conf
        mode: '0644'

    # Ensure the kiosk user exists
    - name: Create kiosk user
      user:
        name: kiosk
        groups: gpio,i2c,video,input,dialout,plugdev
        state: present
        shell: /bin/bash
        home: /home/kiosk
        create_home: true

    # Enable and start watchdog service
    - name: Enable and start watchdog service
      systemd:
        name: watchdog
        enabled: yes
        state: started

    - name: Ensure /etc/X11/Xwrapper.config allows X for any user
      copy:
        dest: /etc/X11/Xwrapper.config
        content: |
          allowed_users=anybody
          needs_root_rights=yes
        owner: root
        group: root
        mode: '0644'
